const fs = require('fs');
const path = require('path');
const packageJson = require('./package.json');

const versionFilePath = path.join(__dirname, 'src', 'version.ts');
let version = Math.floor(new Date().getTime()/1000.0) - 1000000000;
const versionContent = `
// This file is automatically generated before each build
export const version = {
  version: '${packageJson.version}',
  buildTime: '${version}'
};
`;

fs.writeFileSync(versionFilePath, versionContent);
console.log('Version file generated:', versionFilePath, version);
